### ISSUE TITLE
Participantes como Contribuidores

### ISSUE THREAD

**Issue by jlsilva01** [JoelFrancisco/sistema-imoveis-basico#1]
Ola pessoal, onde estão os demais participantes do grupo cadastrados como contribuidores?
Temos somente 3 até este momento.

**Comment by JoelFrancisco** [comment]
Olá, atualmente todos estão cadastrados como colaboradores
![image](https://github.com/JoelFrancisco/sistema-imoveis-basico/assets/69012524/c490d173-9005-42b3-a62a-b909df8b6431)

Mas como por hora só três tiveram necessidade de fazer algum commit no repositório apenas esses aparecem como contribuidores 
![image](https://github.com/JoelFrancisco/sistema-imoveis-basico/assets/69012524/ff9aa74a-6acd-476c-8c7d-1f7a53f3c215)
![image](https://github.com/JoelFrancisco/sistema-imoveis-basico/assets/69012524/cd050982-4158-4190-8700-ce2f04234e1b)

Iremos resolver isso com os outros membros realizando commits no repositório para aparecerem como contribuidores
